# -*- coding: utf-8 -*-
"""Aula de Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OeTfq_UeXiUN2DqyNsBe8rv6mq05sli3
"""

nome = "Ana"

print(nome)

idade = 27

idade + 3

idade

idade = idade + 3

idade

def batata_doce(idade): 
  print("Estou dentro da função")             
  return idade + 1

def menos_um_ano(idade):
  return idade - 1

batata_doce(30)

menos_um_ano(31)

livro1 = "Harry Potter"

livro2 = "Os segredos da mente milionária"

livro3 = "50 tons de cinza"

livro4 = "O pequeno principe"

print(livro1)

print(livro4)

livros = ["Harry Potter" , "Os segredos da mente milionária", "50 tons de cinza", "O pequeno principe"]

print(livros)

livros = [livro1, livro2, livro3, livro4]

print(livros)

def imprime_livros(livros_que_quero_imprimir):
  print("Esses são meus livros:")
  print(livros_que_quero_imprimir)

imprime_livros(livros)

livros

livros[1]

livros[0]

livros[3]

livros[-1]

livros[-2]

livros[2:]

livros

livros[1:]

def imprime_livros(livros_que_quero_imprimir):
  print("Esses são meus livros: ")
  for livro in livros_que_quero_imprimir:
    print(livro)

imprime_livros(livros)

n1 = int(input("Entre com a primeira nota: "))
n2 = int(input("Entre com a segunda nota: "))
n3 = int(input("Entre com a terceira nota: "))
n4 = int(input("Entre com a quarta nota: "))

media = float(n1 + n2 + n3 + n4)/4

print(f'A média é: {media}')

perguntas = ['Telefonou para a vítima?', 'Esteve no local do crime?', 
             'Mora perto da vítima?', 'Devia para a vítima?', 
             'Já trabalhou com a vítima?']

pontos = 0
for pergunta in perguntas:
  print(pergunta)
  print(pontos)

  reposta = input("Responda sim ou não: ").lower().replace('ã', 'a')

  if(reposta == 'sim'):
    pontos = pontos + 1
  
if pontos == 2:
  print("Essa pessoa é suspeita...")

elif 3 <= pontos >5:
  print("Essa pessoa é cúmplice")

elif pontos == 5:
  print("Essa pessoa é assassina")

else:
  print("Essa pessoa é inocente")

dados = {"nome" : "João", "idade" : 27 }

dados["idade"]